services:
  - type: web
    name: jobcard
    env: docker
    plan: free
    autoDeploy: true

    routes:
      # Redirect root (/) to jobcard/index.html
      - type: redirect
        source: /
        destination: /jobcard/index.html
