name: Health Check

on:
  schedule:
    - cron: '*/10 * * * *'
  workflow_dispatch:

jobs:
  check-health:
    runs-on: ubuntu-latest

    steps:
      - name: Check Health Endpoint
        run: |
          response=$(curl -s -o /dev/null -w "%{http_code}" https://jobcard-l7c6.onrender.com/jobcard/actuator/health)
          echo "HTTP Status Code: $response"
          if [ "$response" -ne 200 ]; then
            echo "Health check failed!"
            exit 1
          fi
